# Generated by Django 4.1.3 on 2022-11-27 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.IntegerField(default=1)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
                ('organizationName', models.CharField(default='None', max_length=100)),
                ('contactNumber', models.CharField(default='None', max_length=50)),
                ('activationStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
